create table IF NOT EXISTS NOTIFICACOES(
	UF										varchar,
	TIPO_ENTRADA_VIGIMED					varchar,
	RECEBIDO_DE								varchar,	
	IDENTIFICACAO_NOTIFICACAO				varchar PRIMARY KEY,
	DATA_INCLUSAO_SISTEMA					INT,
	DATA_ULTIMA_ATUALIZACAO					INT,
	DATA_NOTIFICACAO						INT,
	TIPO_NOTIFICACAO						varchar,
	NOTIFICACAO_PARENT_CHILD				varchar,
	DATA_NASCIMENTO							INT,
	IDADE_MOMENTO_REACAO					varchar,
	GRUPO_IDADE								varchar,
	IDADE_GESTACIONAL_MOMENTO_REACAO		varchar,
	SEXO									varchar,
	GESTANTE								varchar,
	LACTANTE								varchar,
	PESO_KG									FLOAT,
	ALTURA_CM								varchar,
	REACAO_EVENTO_ADVERSO_MEDDRA			varchar,
	GRAVE									varchar,
	GRAVIDADE								varchar,
	DESFECHO								varchar,
	DATA_INICIO_HORA						varchar,
	DATA_FINAL_HORA							varchar,
	DURACAO									varchar,
	RELACAO_MEDICAMENTO_EVENTO				varchar,
	NOME_MEDICAMENTO_WHODRUG				varchar,
	ACAO_ADOTADA							varchar,
	NOTIFICADOR								varchar
);

create table IF NOT EXISTS REACOES(
	IDENTIFICACAO_NOTIFICACAO						varchar,
	REACAO_EVTO_ADVERSO_MEDDRA_LLT		 			varchar,
	PT												varchar,
	HLT												varchar,
	HLGT											varchar,
	SOC												varchar,
	DATA_INICIO_HORA								varchar,
	DATA_FINAL_HORA									varchar,
	DURACAO											varchar,
	GRAVE											varchar,
	GRAVIDADE										varchar,
	DESFECHO										varchar,
	FOREIGN KEY(IDENTIFICACAO_NOTIFICACAO) REFERENCES NOTIFICACOES(IDENTIFICACAO_NOTIFICACAO)
);

create table IF NOT EXISTS MEDICAMENTOS(
	IDENTIFICACAO_NOTIFICACAO						varchar,
	RELACAO_MEDICAMENTO_EVENTO 						varchar,
	NOME_MEDICAMENTO_WHODRUG						varchar,
	PRINCIPIOS_ATIVOS_WHODRUG						varchar,
	CODIGO_ATC										varchar,
	DETENTOR_REGISTRO								varchar,
	CONCENTRACAO									varchar,
	COMPONENTE_SUSPEITO								varchar,
	ACAO_ADOTADA									varchar,
	PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO	varchar,
	INDICACAO_MEDDRA								varchar,
	INDICACAO_RELATADA_NOTIFICADOR_INICIAL			varchar,
	DOSE											varchar,
	FREQUENCIA_DOSE									varchar,
	POSOLOGIA										varchar,
	DURACAO											varchar,
	INICIO_ADMINISTRACAO							varchar,
	FIM_ADMINISTRACAO								varchar,
	FORMA_FARMACEUTICA								varchar,
	VIA_ADMINISTRACAO								varchar,
	VIA_ADMINISTRACAO_MAE_PAI						varchar,
	NUMELO_LOTE										varchar,
	FOREIGN KEY(IDENTIFICACAO_NOTIFICACAO) REFERENCES NOTIFICACOES(IDENTIFICACAO_NOTIFICACAO)
);

